In [1]:
import numpy as np
import tensorflow as tf
import gym
import matplotlib.pyplot as plt

In [2]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, InputLayer, Softmax
from tensorflow.keras.layers import Dense, Flatten, BatchNormalization, Lambda
from tensorflow.keras.optimizers import Adam

In [3]:
model = "CartPole-v1"

In [4]:
env = gym.make(model)

In [5]:
env.reset()

array([-0.03114509, -0.03567674,  0.01939409, -0.04577029])

In [34]:
model = "FrozenLake-v0"
env = gym.make(model)
print(env.observation_space)
print(env.action_space)
print(env.reset())

Discrete(16)
Discrete(4)
0


In [20]:
env.action_space.n

2

In [9]:
env.step(0)

(array([-0.03185863, -0.23107135,  0.01847868,  0.252968  ]), 1.0, False, {})

In [25]:
for i_episode in range(2):
    observation = env.reset()
    for t in range(100):
        env.render()
        #print(observation)
        action = env.action_space.sample()
        observation, reward, done, info = env.step(action)
        if done:
            #print("Episode finished after {} timesteps".format(t+1))
            break
env.close()

In [26]:
env.reset()

array([ 0.04957779, -0.01370593, -0.01536431, -0.01101012])

In [65]:
data = tf.keras.datasets.boston_housing.load_data()

In [81]:
def NeuralNet(data, batch_size) :
    net = tf.layers.dense(inputs = data, units = 16, activation = "relu", kernel_initializer = tf.initializers.random_normal)
    net = tf.layers.dense(inputs = net, units = 16, activation = "relu", kernel_initializer = tf.initializers.random_normal)
    net = tf.layers.dense(inputs = net, units = 1, activation = None, kernel_initializer = tf.initializers.random_normal)
    #squared_error = tf.square(net - actual)
    #sum_squared_error = tf.reduce_sum(squared_error)
    return(net)

In [90]:
data[0][0].shape

(404, 13)

In [82]:
net = NeuralNet(data[0][0], 10)

AttributeError: 'tuple' object has no attribute 'ndims'

In [44]:
def getAction(observation, activation = tf.tanh) :
    observation_dim = observation.shape
    net = observato
    policy = Sequential()
    policy.add(InputLayer(input_shape = [None, observation_dim[0]]))
    policy.add(Dense(units = 32, activation = activation))
    policy.add(Dense(units = 32, activation = activation))
    policy.add(Dense(units = 1, activation = tf.sigmoid))
    
    return(policy)

In [45]:
policy = getAction(env.reset())

In [46]:
x = env.reset()

In [60]:
init = tf.global_variables_initializer()
with tf.Session() as sess :    
    sess.run(init)
    policy = getAction(env.reset())
    sess.run(policy.weights[0])

FailedPreconditionError: Error while reading resource variable dense_12/kernel from Container: localhost. This could mean that the variable was uninitialized. Not found: Resource localhost/dense_12/kernel/N10tensorflow3VarE does not exist.
	 [[node dense_12/kernel/Read/ReadVariableOp (defined at <ipython-input-44-07e8491d4f7b>:6)  = ReadVariableOp[dtype=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](dense_12/kernel)]]

Caused by op 'dense_12/kernel/Read/ReadVariableOp', defined at:
  File "/home/ieshan/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ieshan/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ieshan/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/home/ieshan/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/ieshan/anaconda3/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 486, in start
    self.io_loop.start()
  File "/home/ieshan/anaconda3/lib/python3.6/site-packages/tornado/platform/asyncio.py", line 127, in start
    self.asyncio_loop.run_forever()
  File "/home/ieshan/anaconda3/lib/python3.6/asyncio/base_events.py", line 427, in run_forever
    self._run_once()
  File "/home/ieshan/anaconda3/lib/python3.6/asyncio/base_events.py", line 1440, in _run_once
    handle._run()
  File "/home/ieshan/anaconda3/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/home/ieshan/anaconda3/lib/python3.6/site-packages/tornado/platform/asyncio.py", line 117, in _handle_events
    handler_func(fileobj, events)
  File "/home/ieshan/anaconda3/lib/python3.6/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/ieshan/anaconda3/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 450, in _handle_events
    self._handle_recv()
  File "/home/ieshan/anaconda3/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 480, in _handle_recv
    self._run_callback(callback, msg)
  File "/home/ieshan/anaconda3/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 432, in _run_callback
    callback(*args, **kwargs)
  File "/home/ieshan/anaconda3/lib/python3.6/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/ieshan/anaconda3/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/home/ieshan/anaconda3/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 233, in dispatch_shell
    handler(stream, idents, msg)
  File "/home/ieshan/anaconda3/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "/home/ieshan/anaconda3/lib/python3.6/site-packages/ipykernel/ipkernel.py", line 208, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/home/ieshan/anaconda3/lib/python3.6/site-packages/ipykernel/zmqshell.py", line 537, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/home/ieshan/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2662, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "/home/ieshan/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2785, in _run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/home/ieshan/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2903, in run_ast_nodes
    if self.run_code(code, result):
  File "/home/ieshan/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2963, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-60-260ae1523a9a>", line 4, in <module>
    policy = getAction(env.reset())
  File "<ipython-input-44-07e8491d4f7b>", line 6, in getAction
    policy.add(Dense(units = 32, activation = activation))
  File "/home/ieshan/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/checkpointable/base.py", line 474, in _method_wrapper
    method(self, *args, **kwargs)
  File "/home/ieshan/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/engine/sequential.py", line 175, in add
    output_tensor = layer(self.outputs[0])
  File "/home/ieshan/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 746, in __call__
    self.build(input_shapes)
  File "/home/ieshan/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/layers/core.py", line 944, in build
    trainable=True)
  File "/home/ieshan/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 609, in add_weight
    aggregation=aggregation)
  File "/home/ieshan/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/checkpointable/base.py", line 639, in _add_variable_with_custom_getter
    **kwargs_for_getter)
  File "/home/ieshan/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1977, in make_variable
    aggregation=aggregation)
  File "/home/ieshan/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 183, in __call__
    return cls._variable_v1_call(*args, **kwargs)
  File "/home/ieshan/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 146, in _variable_v1_call
    aggregation=aggregation)
  File "/home/ieshan/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 125, in <lambda>
    previous_getter = lambda **kwargs: default_variable_creator(None, **kwargs)
  File "/home/ieshan/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 2437, in default_variable_creator
    import_scope=import_scope)
  File "/home/ieshan/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 187, in __call__
    return super(VariableMetaclass, cls).__call__(*args, **kwargs)
  File "/home/ieshan/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 297, in __init__
    constraint=constraint)
  File "/home/ieshan/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 449, in _init_from_args
    value = self._read_variable_op()
  File "/home/ieshan/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 727, in _read_variable_op
    self._dtype)
  File "/home/ieshan/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_resource_variable_ops.py", line 508, in read_variable_op
    "ReadVariableOp", resource=resource, dtype=dtype, name=name)
  File "/home/ieshan/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/ieshan/anaconda3/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/home/ieshan/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
    op_def=op_def)
  File "/home/ieshan/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

FailedPreconditionError (see above for traceback): Error while reading resource variable dense_12/kernel from Container: localhost. This could mean that the variable was uninitialized. Not found: Resource localhost/dense_12/kernel/N10tensorflow3VarE does not exist.
	 [[node dense_12/kernel/Read/ReadVariableOp (defined at <ipython-input-44-07e8491d4f7b>:6)  = ReadVariableOp[dtype=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](dense_12/kernel)]]


In [ ]:
N = 10
J = 0
for i in range(N) :
    

In [42]:
logits = [0.1, 0.4, 0.5]

In [50]:
dist = tf.distributions.Categorical(probs = logits)

In [58]:
x = dist.log_prob(0)

In [59]:
with tf.Session() as sess :
    y = sess.run(x)

In [60]:
y

-2.3025851

In [57]:
np.log(logits)

array([-2.30258509, -0.91629073, -0.69314718])

In [61]:
a = np.array([1, 2])
b = np.array([3, 4])

In [62]:
np.concatenate((a, b))

array([1, 2, 3, 4])

In [63]:
a * b

array([3, 8])

In [64]:
x = np.arange(0, 11, 1)

In [67]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [69]:
x[::-1].cumsum()[::-1]

array([55, 55, 54, 52, 49, 45, 40, 34, 27, 19, 10])

In [77]:
y = (x - np.mean(x)) / np.std(x)

In [82]:
np.std(x)

3.1622776601683795